# -*- coding: utf-8 -*-
"""Script to replace the first number in file.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EHfp30UxY6IUPvnyoD4n9-1pmyCwvBc5
"""

import os

from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive')

# Set the directory path in your Google Drive
drive_directory_path = "/content/drive/MyDrive/YOLOv8/data400/train/labels"

# List all files in the directory
files = os.listdir(drive_directory_path)

# Iterate through each file
for file_name in files:
    if file_name.endswith(".txt"):  # Ensure it's a txt file
        file_path = os.path.join(drive_directory_path, file_name)
        # Read the content of the file
        with open(file_path, 'r') as file:
            content = file.read()

        # Split the content into lines
        lines = content.split('\n')

        # Iterate through each line and update the first number
        for i, line in enumerate(lines):
            numbers = line.split()
            if numbers:  # Check if the line is not empty
                numbers[0] = '0'  # Replace the first number with 0

            # Update the line in the list of lines
            lines[i] = ' '.join(numbers)

        # Join the lines back into a single string
        updated_content = '\n'.join(lines)

        # Write the updated content back to the file
        with open(file_path, 'w') as file:
            file.write(updated_content)