# -*- coding: utf-8 -*-
"""Overlay bounding box.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XS6KlqRe-Txap8gkpeUFT2biP2AW0P92
"""

import cv2
import numpy as np

from google.colab import drive
drive.mount('/content/drive')

from google.colab.patches import cv2_imshow
import cv2

def convert_coordinates_to_pixels(coords, image_shape):
    height, width, _ = image_shape
    x_center, y_center, w, h = coords
    x = int((x_center - w / 2) * width)
    y = int((y_center - h / 2) * height)
    w = int(w * width)
    h = int(h * height)
    return x, y, w, h

def draw_boxes(image_path, coordinates1, coordinates2, output_path):
    # Read the image
    image = cv2.imread(image_path)

    # Convert normalized coordinates to pixel values
    x1, y1, w1, h1 = convert_coordinates_to_pixels(coordinates1, image.shape)
    x2, y2, w2, h2 = convert_coordinates_to_pixels(coordinates2, image.shape)

    # Draw bounding box from the first set of coordinates (in green)
    cv2.rectangle(image, (x1, y1), (x1+w1, y1+h1), (0, 255, 0), 2)

    # Draw bounding box from the second set of coordinates (in red)
    cv2.rectangle(image, (x2, y2), (x2+w2, y2+h2), (0, 0, 255), 2)

    # Save the output image
    cv2.imwrite(output_path, image)

    # Display the image using cv2_imshow for Colab
    cv2_imshow(image)

# Example usage
image_path = '/content/drive/MyDrive/YOLOv8/data800/test/images/IMG_6171.JPEG'
coordinates1 = [0.584961, 0.533203, 0.246094, 0.263021]
coordinates2 = [0.590832, 0.543828, 0.264311, 0.286225]
output_path = '/content/drive/MyDrive/YOLOv8/image_with_boxes1.jpg'

draw_boxes(image_path, coordinates1, coordinates2, output_path)



from google.colab.patches import cv2_imshow
import cv2

def draw_boxes(image_path, coordinates1, coordinates2, output_path):
    # Read the image
    image = cv2.imread(image_path)

    # Get image dimensions
    height, width, _ = image.shape

    # Convert normalized coordinates to pixel values
    x1, y1, w1, h1 = map(int, [coord * width if i % 2 == 0 else coord * height for i, coord in enumerate(coordinates1)])
    x2, y2, w2, h2 = map(int, [coord * width if i % 2 == 0 else coord * height for i, coord in enumerate(coordinates2)])

    # Draw bounding box from the first set of coordinates (in green)
    cv2.rectangle(image, (x1, y1), (w1, h1), (0, 255, 0), 2)

    # Draw bounding box from the second set of coordinates (in red)
    cv2.rectangle(image, (x2, y2), (w2, h2), (0, 0, 255), 2)

    # Save the output image
    cv2.imwrite(output_path, image)

    # Display the image using cv2_imshow for Colab
    cv2_imshow(image)

# Example usage
image_path = '/content/drive/MyDrive/YOLOv8/data800/test/images/IMG_6171.JPEG'
coordinates1 = [0.584961, 0.533203, 0.246094, 0.263021]
coordinates2 = [0.590832, 0.543828, 0.264311, 0.286225]
output_path = '/content/drive/MyDrive/YOLOv8/image_with_boxes2.jpg'

draw_boxes(image_path, coordinates1, coordinates2, output_path)