# -*- coding: utf-8 -*-
"""Yolo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X4uOtso3pXZZTcoDap-FvOYk0Z9VNjwf
"""

"""
YOLOv8 Eye Detection — Python Script Version
Converted from Google Colab notebook format to standalone .py script.

Usage:
    python yolov8_predict.py
"""

import os
import shutil
import subprocess
from pathlib import Path
from ultralytics import YOLO

# ==========================================================
# (OPTIONAL) Mount Google Drive (uncomment if running in Colab)
# from google.colab import drive
# drive.mount('/content/drive')
# ==========================================================

# ==========================================================
# Install and environment check (run once manually if needed)
# ==========================================================
# pip install -U ultralytics

# ==========================================================
# Paths (EDIT THESE AS REQUIRED)
# ==========================================================
model_path = "/content/drive/MyDrive/YOLOv8/best.pt"               # trained weights
images_dir = "/content/drive/MyDrive/YOLOv8/mac_maybe_4may_v3"     # input folder
project_dir = "/content/drive/MyDrive/YOLOv8/output"               # output base directory
run_name = "eye_boxes"                                             # run tag

# ==========================================================
# Overwrite behaviour
# ==========================================================
OVERWRITE_PREVIOUS_RUN = False
run_dir = os.path.join(project_dir, run_name, "predict")

if OVERWRITE_PREVIOUS_RUN and os.path.isdir(run_dir):
    shutil.rmtree(run_dir)

# ==========================================================
# Load the model
# ==========================================================
model = YOLO(model_path)

# ==========================================================
# Run inference
# ==========================================================
results = model.predict(
    source=images_dir,
    imgsz=640,
    conf=0.35,
    iou=0.30,
    max_det=1,         # set =1 for single eye detection
    save=True,
    save_txt=True,
    project=project_dir,
    name=run_name
)

# ==========================================================
# Output summary
# ==========================================================
print("\n==================== YOLOv8 Prediction Complete ====================")
print("Annotated images saved at:", run_dir)
print("Labels folder:", os.path.join(run_dir, "labels"))

print("\nDirectory contents:")
for root, dirs, files in os.walk(run_dir):
    level = root.replace(run_dir, "").count(os.sep)
    indent = " " * 4 * level
    print(f"{indent}{os.path.basename(root)}/")
    subindent = " " * 4 * (level + 1)
    for f in files:
        print(f"{subindent}{f}")

# ==========================================================
# (OPTIONAL) Export zipped results
# ==========================================================
# shutil.make_archive(run_name, 'zip', os.path.join(project_dir, run_name))
# print(f"Zipped results exported: {run_name}.zip")