# -*- coding: utf-8 -*-
"""Append

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZnozJs4wigqHw7oG1iukXllYWTUrZ1tq
"""

# Import necessary libraries
import pandas as pd

# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')


# Path to your dataset on Google Drive
csv_path = '/content/drive/My Drive/Deep learning model/Pinkeye/Pinkeye.csv'

# Load the CSV file into a DataFrame
df = pd.read_csv(csv_path)

# Check if the necessary columns exist
if 'stage' not in df.columns:
    raise KeyError("Column 'stage' not found in the CSV file.")

# Add the new 'stage_binary' column
df['stage_binary'] = df['stage'].apply(lambda x: 'Yes' if x == 'A' else 'No')

# Save the updated DataFrame back to the same CSV file
df.to_csv(csv_path, index=False)

print(f"Updated CSV saved successfully to: {csv_path}")

# Remove any 'Unnamed' columns
df = df.loc[:, ~df.columns.str.contains('^Unnamed')]

# Save the updated DataFrame back to the same CSV file
df.to_csv(csv_path, index=False)

print(f"Updated CSV saved successfully to: {csv_path}")

# Add the A1_2 column
def generate_a1_2(stage, severity):
    if stage == "A" and severity in [1, 2]:
        return f"{stage}{severity}"
    else:
        return f"{stage}{severity}"  # Preserve original values

# Apply the function to generate A1_2 column
df['A1_2'] = df.apply(lambda row: generate_a1_2(row['stage'], row['severity']), axis=1)

# Save the updated DataFrame back to the same CSV file
df.to_csv(csv_path, index=False)

print(f"Updated CSV saved successfully with A1_2 column at: {csv_path}")

# Simplify the A1_2 column
def simplify_a1_2(value):
    if value.startswith("S"):
        return "S"  # Group all S1–S4 into S
    elif value.startswith("R"):
        return "R"  # Group all R1–R4 into R
    elif value == "Normal0":
        return "Normal"  # Simplify Normal0 into Normal
    else:
        return value  # Retain other values (e.g., A1, A2)

# Apply the function to simplify the A1_2 column
df['A1_2'] = df['A1_2'].apply(simplify_a1_2)

# Save the updated DataFrame back to the same CSV file
df.to_csv(csv_path, index=False)

print(f"Updated A1_2 column saved successfully to: {csv_path}")